config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :articles
  resources :users, :only => [:index, :edit, :update]
  resources :subcategories
  resources :categories
  get 'edit', to: 'edit#edit'
  devise_for :users
root to: 'categories#index'
get 'search', to: 'search#search'
get 'users_search', to: 'users#search'
get 'articles_search', to: 'articles#search'

#get “search”, to: “search#search”

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  end
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  include SearchFlip::Model
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :category
  has_many :articles, dependent: :destroy
  validates :title, presence: true, length: {minimum: 3}
  validates :text, presence: true
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[ show edit update destroy ]


  # GET /subcategories or /subcategories.json
  def index
    @categories = Category.all
    cate = params[:category]

   if !cate.nil?
     @subcategories = Subcategory.where(:category_id => cate)
   else
     @subcategories = Subcategory.all
   end
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories or /subcategories.json
  def create
    authorize Subcategory
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to subcategory_url(@subcategory), notice: "Subcategory was successfully created." }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    authorize Subcategory
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to subcategory_url(@subcategory), notice: "Subcategory was successfully updated." }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    authorize Subcategory
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: "Subcategory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subcategory_params
      params.require(:subcategory).permit(:title, :text, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<div class="flex-row d-flex justify-content-center">

<div class="col-md-8">
<div class="card mt-5">

    <div class="card-body">
    <%= form_for @subcategory do |f| %>


    <div class="form-group">
    <%= markdown f.label :title%>
    <%= markdown f.text_field :title, class: 'form-control' %>

    </div>

    <div class="form-group">


    <%= f.label :text%>
    <%= f.text_area :text, class: 'form-control'%>

    </div>

  <%= f.select :category_id, Category.all.map {|c| [c.title, c.id]} %>

  <div>
    <%= f.submit I18n.t('create_subcategory') %>
  </div>
<% end %>

app/views/subcategories/_subcategory.html.erb
<div id="<%= dom_id subcategory %>">
  <p>
    <strong>Title:</strong>
    <%= subcategory.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= subcategory.text %>
  </p>

</div>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render "form", subcategory: @subcategory %>

<br>

<div>
  <%= link_to "Show this subcategory", @subcategory %> |
  <%= link_to "Back to subcategories", subcategories_path %>
</div>

app/views/subcategories/index.html.erb
<div class="container">
    <div class="row">


    <div class="col-md-8">

    <div class="row">

        <h6><%= I18n.t('find_subcategories') %>:</h6>
        <form action="/search" method="get">
          <%= hidden_field_tag "locale", params[:locale]%>
          <div class="input-group input-inline search">
            <input class="form-input" type="text" name="query" placeholder=<%=I18n.t('search')%>>
             <button class="btn btn-primary input-group-btn "><%=I18n.t('search')%></button>
               </div>
              </form>


     <% @subcategories.each do |subcategory| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                  <h3><%= link_to subcategory.title, subcategory_path(subcategory.id) %></h3>

                    <%= link_to I18n.t('view'), subcategory_path(subcategory.id), class: 'btn btn-primary'%>
                </div>
            </div>
         </div>
      <% end %>
  </div>
</div>



    <div class="col-md-4">
      <div class="card mt-3">
        <div class="card-header">
            <%= I18n.t('all_categories') %>
          </div>
            <div class="card-body">
              <ul class="list-group">
                <% @categories.each do |category| %>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                     <%= link_to category.title, subcategories_path(:category => category.id) %>
                     </li>
                      <% end %>
                        </ul>
                       </div>
                     </div>
                     </div>
                   </div>
                  </div>

app/views/subcategories/new.html.erb
<h1><%= I18n.t('new_subcategory')%></h1>

<%= render "form", subcategory: @subcategory %>

<br>

<div>
  <%= link_to I18n.t('back_to_subcategories'), subcategories_path %>
</div>

app/views/subcategories/show.html.erb
<div class="container-fluid mt-3">
  <h1><%= I18n.t('categories') %>: <%= link_to @subcategory.category.title, category_path(@subcategory.category.id)%></h1>
  <p>
    <strong><%= I18n.t('title') %>:</strong>
    <%= @subcategory.title %>
  </p>

  <p>
    <strong><%= I18n.t('body') %>:</strong>
    <%= markdown(@subcategory.text) %>
  </p>



<%= link_to I18n.t('edit'), edit_subcategory_path(@subcategory.id), class: 'btn btn-primary' if moderator? || admin? %>
<%= button_to I18n.t('delete'), subcategory_path(@subcategory.id), method: :delete, class: 'btn btn-danger' if admin? %>
<%= link_to I18n.t('back'), category_path(@subcategory.category.id), class: 'btn btn-secondary'%>
</div>


<% @subcategory.articles.each do |article| %>
   <div class="col-md-6">
       <div class="card mt-3">
           <div class="card-body">
             <h3><%= link_to article.title, article_path(article.id) %></h3>
           </div>
       </div>
    </div>
<% end %>



<div class="col-md-4">