config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :articles
  resources :users, :only => [:index, :edit, :update]
  resources :subcategories
  resources :categories
  get 'edit', to: 'edit#edit'
  devise_for :users
root to: 'categories#index'
get 'search', to: 'search#search'
get 'users_search', to: 'users#search'
get 'articles_search', to: 'articles#search'

#get “search”, to: “search#search”

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include SearchFlip::Model
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :subcategory
  validates :title, presence: true, length: {minimum: 3}
  validates :body, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    authorize Article
    @subcategories = Subcategory.all
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    authorize Article
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    authorize Article
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    authorize Article
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def search
    @query = ArticleIndex.search(params[:query].to_s).page(params[:page]).per(50)

    @query = @query.page(params[:page]).per(50)

    @results = @query.records
    @total_results = @query.total_entries
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :subcategory_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

app/views/articles/_form.html.erb
<div class="flex-row d-flex justify-content-center">

<div class="col-md-8">
<div class="card mt-5">

    <div class="card-body">
    <%= form_for @article do |f| %>


    <div class="form-group">
    <%= markdown f.label :title%>
    <%= markdown f.text_field :title, class: 'form-control' %>

    </div>

    <div class="form-group">


    <%= f.label :body%>
    <%= f.text_area :body, class: 'form-control'%>

    </div>

  <%= f.select :subcategory_id, Subcategory.all.map {|c| [c.title, c.id]} %>

  <div>
    <%= f.submit I18n.t('new_article')  %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
    <div class="row">


    <div class="col-md-8">

    <div class="row">
      <h6><%= I18n.t('find_article') %>:</h6>
      <form action="/articles_search" method="get">
        <%= hidden_field_tag "locale", params[:locale]%>
        <div class="input-group input-inline search">
          <input class="form-input" type="text" name="query" placeholder=<%=I18n.t('search')%>>
           <button class="btn btn-primary input-group-btn "><%=I18n.t('search')%></button>
             </div>
            </form>


     <% @articles.each do |article| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                  <h3><%= link_to article.title, article_path(article.id) %></h3>

                    <%= link_to I18n.t('view'), article_path(article.id), class: 'btn btn-primary'%>
                </div>
            </div>
         </div>
      <% end %>
  </div>
</div>

<div class="col-md-4">
  <div class="card mt-3">
    <div class="card-header">
        <%= I18n.t('all_subcategories') %>
      </div>
        <div class="card-body">
          <ul class="list-group">
            <% @subcategories.each do |subcategory| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                 <%= link_to subcategory.title, subcategories_path(:subcategory => subcategory.id)%>
                 </li>
                  <% end %>
                    </ul>
                   </div>
                 </div>
                 </div>
               </div>
              </div>

app/views/articles/new.html.erb
<h1> <%= I18n.t('new_article') %></h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to I18n.t('back'), articles_path %>
</div>

app/views/articles/search.html.erb
<% if @results.any? %>
  <h3><%= I18n.t('results')%>(<%= @total_results %>):</h3>
  <ol>
  <% @results.each do |article| %>
    <li><%= link_to article.title, article_path(article.id) %> Subcategory: <%= link_to article.subcategory.title, subcategory_path(article.subcategory.id) %></li>
  <% end %>
  </ol>
<% else %>
  Results not found :(
<% end %>


<%= paginate @query %>

app/views/articles/show.html.erb
<div class="container-fluid mt-3">
  <h3><%= I18n.t('subcategory') %>: <%= link_to @article.subcategory.title, subcategory_path(@article.subcategory.id)%></h3>
  <p>
    <strong><%= I18n.t('title') %>:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong><%= I18n.t('body') %>:</strong>
    <%= markdown(@article.body) %>
  </p>



<%= link_to I18n.t('edit'), edit_article_path(@article.id), class: 'btn btn-primary' if moderator? || admin? %>
<%= button_to I18n.t('delete'), article_path(@article.id), method: :delete, class: 'btn btn-danger' if admin? %>
<%= link_to I18n.t('back'), subcategory_path(@article.subcategory.id), class: 'btn btn-secondary'%>
</div>






<div class="col-md-4">