config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :articles
  resources :users, :only => [:index, :edit, :update]
  resources :subcategories
  resources :categories
  get 'edit', to: 'edit#edit'
  devise_for :users
root to: 'categories#index'
get 'search', to: 'search#search'
get 'users_search', to: 'users#search'
get 'articles_search', to: 'articles#search'

#get “search”, to: “search#search”

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, :optional => true, :class_name => "User",
  :foreign_key => 'user_id'
  has_many :subcategories, dependent: :destroy 
  validates :title, presence: true, length: {minimum: 3}
  validates :text, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    authorize Category
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    authorize Category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    authorize Category
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :text, :user_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>


  <p>
    <strong>Text:</strong>
    <%= category.text %>
  </p>

</div>

app/views/categories/_form.html.erb
<div class="flex-row d-flex justify-content-center">

<div class="col-md-8">
<div class="card mt-5">

    <div class="card-body">
    <%= form_for @category do |f| %>


    <div class="form-group">
    <%= markdown f.label :title%>
    <%= markdown f.text_field :title, class: 'form-control' %>

    </div>

    <div class="form-group">


    <%= f.label :text%>
    <%= f.text_area :text, class: 'form-control'%>

    </div>

    <%= f.submit I18n.t('create_category') %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>


<h1><% I18n.t('categories') %></h1>

<div class="container">
    <div class="row">


    <div class="col-md-8">

    <div class="row">


     <% @categories.each do |category| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                                    <h3><%= link_to category.title, category_path(category.id) %></h3>

                    <%= link_to I18n.t('view'), category_path(category.id), class: 'btn btn-primary'%>
                </div>
            </div>
         </div>
    <% end %>
 </div>
</div>



    <div class="col-md-4">

app/views/categories/new.html.erb
<h1><%= I18n.t('new_category')%></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to I18n.t('back_to_categories'), categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container-fluid mt-3">
  <h1><%= @category.title%></h1>
  <p>

  <p>
    <strong></strong>
    <%= markdown(@category.text) %>
  </p>





<%= link_to I18n.t('edit'), edit_category_path(@category.id), class: 'btn btn-primary'if moderator? || admin? %>
<%= button_to I18n.t('delete'), category_path(@category.id), method: :delete, class: 'btn btn-danger' if admin? %>
<%= link_to I18n.t('back'), categories_path, class: 'btn btn-secondary'%>
</div>

<h3><%=I18n.t('subcategories')%>: </h3>
<div class="col-md-8">

<div class="row">


 <% @category.subcategories.each do |subcategory| %>
    <div class="col-md-6">
        <div class="card mt-3">
            <div class="card-body">
                                <h3><%= link_to subcategory.title, subcategory_path(subcategory.id) %></h3>

                <%= link_to link_to I18n.t('view'), subcategory_path(subcategory.id), class: 'btn btn-primary'%>
            </div>
        </div>
      </div>
   <% end %>
  </div>
</div>



<div class="col-md-4">