config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :articles
  resources :users, :only => [:index, :edit, :update]
  resources :subcategories
  resources :categories
  get 'edit', to: 'edit#edit'
  devise_for :users
root to: 'categories#index'
get 'search', to: 'search#search'
get 'users_search', to: 'users#search'
get 'articles_search', to: 'articles#search'

#get “search”, to: “search#search”

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <a class="navbar-brand" href="#">DocSearch</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to I18n.t('menu.home'), root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to I18n.t('menu.new_category'), new_category_path, class: 'nav-link'if admin? %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('menu.new_subcategory'), new_subcategory_path, class: 'nav-link' if admin? %>
      </li>
      <li class="nav-item">
          <%= link_to I18n.t('new_article'), new_article_path, class: 'nav-link' if admin? %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('all_articles'), articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
            <%= link_to I18n.t('all_subcategories'), subcategories_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to I18n.t('all_categories'), categories_path, class: 'nav-link' %>
      </li>
    </li>
    <li class="nav-item">
        <%= link_to I18n.t('all_users'), users_path, class: 'nav-link' if admin? %>
    </li>
  <li class="nav-item">

      <form action="/articles_search" method="get">
        <%= hidden_field_tag "locale", params[:locale]%>
        <div class="input-group input-inline search">
          <input class="form-input" type="text" name="query" placeholder=<%=I18n.t('search')%>>
           <button class="btn btn-primary input-group-btn mb1 black mb1 bg-black"><%=I18n.t('search')%></button>
             </div>
            </form>
      </li>
       <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if user_signed_in? %>
        <li><%= button_to I18n.t('menu.log_out'), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to I18n.t('sign_in'), new_user_session_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %></li>/
          <li><%= link_to I18n.t('sign_up'), new_user_registration_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %></li>
        <% end %>

  </div>
</nav>


<ul>
<li><%= link_to 'English', root_path(locale: :en) %></li>
<li><%= link_to 'Українська', root_path(locale: :ua) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocSearth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>


<body>
    <%= render "layouts/navigation" %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>



    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>

</html>